name: Build Kernel - Android 12
on: 
  workflow_dispatch:
    inputs:
      test:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  build-kernel:
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        include:
          - sub_level: 66
            os_patch_level: 2021-11
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android12-5.10
      version_name: android12-5.10.${{ matrix.sub_level }}
      tag: android12-5.10-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: "5.10"
